name: Coding Style

on: [push, pull_request]

jobs:
    nette_cc:
        name: Nette Code Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none

            - run: composer create-project nette/code-checker temp/code-checker ^3 --no-progress
            - run: php temp/code-checker/code-checker --no-progress
